#!/usr/bin/env bash

# Curl down homebrew
NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# Setup env for brew mngt
echo >> /Users/$(whoami)/.bash_profile
echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/$(whoami)/.bash_profile
eval "$(/opt/homebrew/bin/brew shellenv)"
