#!/usr/bin/env bash
# Install dotfiles for macos

if [[ -z $STOW_FOLDERS ]]; then
  STOW_FOLDERS="aerospace,bin,ghostty,mac-misc,nvimrc,tmux,vim,zathura,zsh,sketchybar"
fi

if [[ -z $DOTFILES ]]; then
  DOTFILES=$HOME/.dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
